[package]
name = "treesitter"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.102"
mlua = { version = "0.11.6", features = ["lua54", "anyhow"] }
tree-sitter = "0.26.8"
tree-sitter-highlight = "0.26.8"
tree-sitter-lua = "0.5.0"
tree-sitter-lyra = {
    branch="main",
    git="https://github.com/HasSak-47/tree-sitter-lyra.git",
}
