#ifndef __CLI_BIND_GEN__
#define __CLI_BIND_GEN__

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include "./bindgen_log.h"

struct Args;

void args_delete(struct Args *args);

const char *args_get_cache_path(const struct Args *args);

const char *args_get_config_path(const struct Args *args);

enum Level args_get_level(const struct Args *args);

const char *args_get_script(const struct Args *args);

struct Args *args_parse(int argc, const char *const *argv);

#endif  /* __CLI_BIND_GEN__ */
