#ifndef __LOG_BIND_GEN__
#define __LOG_BIND_GEN__

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

enum Level {
  LEVEL_OFF = 0,
  LEVEL_ERROR = 1,
  LEVEL_WARN = 2,
  LEVEL_INFO = 3,
  LEVEL_DEBUG = 4,
  LEVEL_TRACE = 5,
};

void init_logger(void);

void rust_log(unsigned int line,
              char *file,
              enum Level level,
              char *msg);

void set_log(enum Level level);

#endif  /* __LOG_BIND_GEN__ */
