#ifndef __CLI_GEN__
#define __CLI_GEN__

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

struct Args;

void free_args(struct Args *args);

const char *get_script(const struct Args *args);

bool is_debug(const struct Args *args);

struct Args *parse_args(int argc, const char *const *argv);

#endif  /* __CLI_GEN__ */
