#ifndef __PLUGIN_BIND_GEN__
#define __PLUGIN_BIND_GEN__

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include "lua.h"

enum PluginKind {
  PLUGIN_KIND_LUA = 0,
  PLUGIN_KIND_BINARY = 1,
  PLUGIN_KIND_C = 2,
  PLUGIN_KIND_RUST = 3,
};

struct CIterator______c_char;

struct PluginData;

struct PluginHandler;

struct PluginManager;

typedef struct CIterator______c_char CIteratorString;

void delete_plugin_manager(struct PluginManager *ptr);

struct PluginData *get_plugin(struct PluginManager *manager_ptr,
                              const char *path);

const CIteratorString *get_plugin_dependecies_iterator(struct PluginManager *manager,
                                                       const char *path);

struct PluginHandler *get_plugin_handler(struct PluginData *plugin);

const CIteratorString *get_plugin_iterator(struct PluginManager *manager);

char manager_is_plugin_prepared(struct PluginManager *manager_ptr,
                                const char *path);

int manager_is_plugin_resolved(struct PluginManager *manager,
                               const char *path);

int32_t manager_prepare_plugin(struct PluginManager *manager_ptr,
                               const char *path);

struct PluginData *manager_resolve_plugin(struct PluginManager *manager_ptr,
                                          const char *path);

int32_t manager_unload_plugin(lua_State *lua,
                              struct PluginManager *manager_ptr,
                              const char *path);

struct PluginManager *new_plugin_manager(void);

const char *next_plugin_name(const CIteratorString *iter);

char *plugin_get_compilation_path(const struct PluginData *plugin);

char *plugin_get_data_path(const struct PluginData *plugin);

enum PluginKind plugin_get_kind(struct PluginData *plugin);

char *plugin_get_name(const struct PluginData *plugin);

char *plugin_get_shared_object_path(const struct PluginData *plugin);

char *plugin_get_url(struct PluginData *plugin);

#endif  /* __PLUGIN_BIND_GEN__ */
