#ifndef __PLUGIN_BIND_GEN__
#define __PLUGIN_BIND_GEN__

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include "lua.h"

enum Level {
  LEVEL_ERROR = 0,
  LEVEL_WARN = 1,
  LEVEL_INFO = 2,
  LEVEL_DEBUG = 3,
  LEVEL_TRACE = 4,
};

void init_logger(void);

void rust_log(unsigned int line,
              char *file,
              enum Level level,
              char *msg);

#endif  /* __PLUGIN_BIND_GEN__ */

int32_t manager_unload_plugin(lua_State *lua,
                              struct PluginManager *manager_ptr,
                              const char *path);
