#ifndef __BIND_GEN__
#define __BIND_GEN__

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum PluginKind {
  PLUGIN_KIND_LUA,
  PLUGIN_KIND_C,
} PluginKind;

typedef struct Args Args;

typedef struct Plugin Plugin;

typedef struct PluginManager PluginManager;

const struct Plugin *add_or_get_plugin(struct PluginManager *manager_ptr,
                                       const char *path);

struct Plugin *add_plugin(struct PluginManager *manager_ptr,
                          const char *path);

void delete_plugin_manager(struct PluginManager *ptr);

void free_args(struct Args *args);

struct Plugin *get_plugin(struct PluginManager *manager_ptr,
                          const char *path);

const char *get_script(const struct Args *args);

bool is_debug(const struct Args *args);

char is_plugin_loaded(struct PluginManager *manager_ptr,
                      const char *path);

char mark_plugin_as_loaded(struct PluginManager *manager_ptr,
                           const char *path);

struct PluginManager *new_plugin_manager(void);

struct Args *parse_args(int argc, const char *const *argv);

enum PluginKind plugin_get_kind(struct Plugin *plugin);

char *plugin_get_name(struct Plugin *plugin);

char *plugin_get_path(struct Plugin *plugin);

#endif  /* __BIND_GEN__ */
